version: "3.8"

# 개발 환경용 도커파일 만들기
volumes:
  dev_db: {}

services:
  db:
    image: postgres
    volumes:
      - dev_db:/var/lib/postgresql/data
    ports:
      - 5431:5432
    environment: 
      - POSTGRES_PASSWORD=example
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  web:
    depends_on: 
      - db
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/django_prac
    ports:
      - "8000:8000" 
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=postgres
      - DJANGO_DB_USERNAME=postgres
      - DJANGO_DB_PASSWORD=example
    command: 
      - bash
      - -c
      - |
        bash -c 'while !</dev/tcp/db/5432; do sleep 1; done;'
        cd /django_prac
        source .env
        cd /django_prac/django_project
        python manage.py migrate
        python manage.py inituser
        python manage.py runserver 0:8000
