FROM python:3.9.2
LABEL description="개발용 장고 도커 파일"

RUN apt-get update && apt-get install -y vim

COPY ./requirements.txt .
RUN pip install -r requirements.txt

ENV PYTHONUNBUFFERED 1

CMD ["/bin/bash"]
