# 개발용 도커파일

# postgres 5431:5432 로 띄우기
# redis 6378:6379 로 띄우기
version: "3.8"

volumes:
  postgres_container_volume: {}
  redis_container_volume: {}
  django_container_volume: {}

services:
  postgres_container:
    image: postgres
    ports:
      - 5431:5432
    volumes:
      - postgres_container_volume:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=fortest
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  redis_container:
    image: redis
    ports:
      - 6378:6379
    volumes:
      - redis_container_volume:/data

  django_container:
    depends_on:
      - postgres_container
      - redis_container
    build:
      context: .
      dockerfile: ./dockerfiles/dockerDockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./:/django_prac
    env_file: 
      .env
    command: |      
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done;'
      cd /django_prac/django_project
      python manage.py migrate
      python manage.py inituser
      python manage.py runserver 0:8000
