
version: 2.1

jobs:
  simple_build: # job names
    docker: # docker image
    - image: noname2048/askbanana:simple
      auth:
        username: noname2048 
        password: $DOCKERHUB_PASSWORD
    environment:
      DEBUG: "False"
      DB: "local"
    working_directory: /askbanana/django_project # ~/project # default
    steps:
    - run:
        name: docker compose up
        command: |
          cd /askbanana
          docker-compose -f ./dockerfiles/Dockerfile.django.dev up
    - run:
        name: send to codecov
        command: |
          coverage run ./manage.py test
          codecov -t $CODECOV_TOKEN

workflows:
  version: 2
  test_django_docker: # workflow namespace
    jobs:
    - simple_build:
        filters:
          branches:
            only:
            - main
