
version: 2.1

jobs:
  simple_build: # job names
    docker: # docker image
    - image: noname2048/askbanana:simple
      auth:
        username: noname2048 
        password: $DOCKERHUB_PASSWORD
    environment:
      DEBUG: "False"
      DB: "local"
    # working_directory: /askbanana/django_project # ~/project # default
    working_directory: ~/project
    steps:
    - checkout
    - run:
        name: Install Docker Compose
        command: |
          curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
          chmod +x ~/docker-compose
          mv ~/docker-compose /usr/local/bin/docker-compose
    - run:
        name: docker compose up
        command: |
          cd ~/django-prac-004
          docker-compose -f ./dockerfiles/Dockerfile.django.dev up
    - run:
        name: send to codecov
        command: |
          cd django-prac-004/django_project
          coverage run ./manage.py test
          codecov -t $CODECOV_TOKEN

workflows:
  version: 2
  test_django_docker: # workflow namespace
    jobs:
    - simple_build:
        filters:
          branches:
            only:
            - main
