version: 2.1

jobs:
  build: # job names
    # machine: # machine image @ cicleci
    #  image: ubuntu-2004:202101-01
    docker: # docker image
    - image: python:3.9.2
      auth:
        username: noname2048 
        password: $DOCKERHUB_PASSWORD

    steps:
    - checkout
    - run:
        command: | # multilines string
          pip install --upgrade pip 
          pip install Django

workflows:
  version: 2
  install_django:
    jobs:
    - build
