
version: 2.1

jobs:
  simple_build: # job names
    docker: # docker image
    - image: noname2048/askbanana:simple
      auth:
        username: noname2048 
        password: $DOCKERHUB_PASSWORD
    environment:
      DEBUG: "False"
    working_directory: /askbanana #~/project # default
    steps:
    # - checkout
    # - run:
    #     name: pip install
    #     command: | # multiline string
    #       pip install --upgrade pip 
    #       pip install -r requirements.txt
    # - run:
    #     name: env set
    #     command:
    #       echo $SECRET > .secrets.json
    # - run:
    #     name: manage.py test
    #     command: |
    #       cd django_project
    #       python manage.py test
    - run:
        name: read file dir
        command:
          ls -al >> a.txt && 
          cat a.txt
    # - run:
    #     name: send to codecov
    #     command: |
    #       cd /askbanana/django_proejct
    #       coverage run ./manage.py test
    #       codecov -t $CODECOV_TOKEN

workflows:
  version: 2
  test_django_docker: # workflow namespace
    jobs:
    - simple_build
