version: "3.8"

services:
  gunicorn-app:
    build:
      context: ../
      dockerfile: ./dockerfiles/Dockerfile
    ports:
      - 8001:8005
    volumes:
      - /home/ubuntu/deploy/django-prac-004:/django-prac-004
    env_file:
      - /home/ubuntu/.env
    command:
      - /bin/bash
      - -c
      - |
        cd /django-prac-004
        poetry install --no-dev
        cd /django-prac-004/django_project
        python manage.py migrate --settings=mysite.settings.product
        gunicorn -w 2 -b 0:8005 mysite.wsgi:application \
        --access-logfile gunicorn/access.log \
        --error-logfile gunicorn/error.log 
