version: "3.8"

services:
  gunicorn-app:
    build:
      context: ../
      dockerfile: ./dockerfiles/Dockerfile
    ports:
      - 8002:8005
    volumes:
      - /home/ubuntu/django-prac-004:/django-prac-004
    env_file:
      - /home/ubuntu/django-prac-004/.env
    command:
      - /bin/bash
      - -c
      - |
        cd /django-prac-004/django_project
        gunicorn -w 2 -b 0:8005 mysite.wsgi:application
    