# CI 환경 테스트 pre-built 용 도커 (속도개선을 위함)

# 아래와 같은 명령어로 빌드 & push
# docker build -f dockerfiles/Dockerfile.circleci -t noname2048/askbanana:simple .
# docker push noname2048/askbanana:simple

FROM python:3.8.8
LABEL version="1.0" \
    description="simple django Dockerfile"

ENV PYTHONUNBUFFERED 1
COPY ./requirements.txt .
RUN apt-get update && pip install -r requirements.txt

WORKDIR /askbanana/django_project

CMD ["/bin/bash"]
