# circleci primary docker
# pre-build for build speed
# cd /docker-prac-004
# docker build -f dockerfiles/Dockerfile.circleci -t noname2048/askbanana:simple .
# docker push noname2048/askbanana:simple

FROM python:3.9.2
LABEL version="1.0" \
    description="simple django Dockerfile"

ENV PYTHONUNBUFFERED 1
COPY ./requirements.txt .
RUN apt-get update && pip install -r requirements.txt

WORKDIR /askbanana/django_project

CMD ["/bin/bash"]
