FROM python:3.8.8
LABEL description="for Development Docker Django-apps"

# apt
RUN apt-get update && apt-get install -y --no-install-recommends vim wget apt-utils

# poetry
RUN wget https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py &&\
    python get-poetry.py --yes && \
    rm get-poetry.py
ENV PATH="/root/.poetry/bin:${PATH}"

# dockerize
ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

# wait-for-it
RUN wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh

# requirements
COPY ./requirements.dev.txt .
RUN pip install -r requirements.dev.txt

RUN poetry config virtualenvs.create false
COPY ./pyproject.toml .
COPY ./poetry.lock .
RUN poetry install

ENV PYTHONUNBUFFERED 1

CMD ["/bin/bash"]
