# Generated by Django 3.1.7 on 2021-03-28 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumcategory',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='forumcomment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='forumlike',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='forumtag',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='forumcomment',
            old_name='delete',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='delete',
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.forumcategory'),
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.forumpost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forumlike',
            name='posts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.forumpost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forumpost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.forumcategory'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='tags',
            field=models.ManyToManyField(to='forum.ForumTag'),
        ),
        migrations.AddField(
            model_name='forumtag',
            name='parent_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.forumtag'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
