# Generated by Django 3.1.7 on 2021-04-09 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0004_auto_20210404_2044"),
    ]

    operations = [
        migrations.RenameField(
            model_name="forumpost",
            old_name="author",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="forumpost",
            old_name="ip",
            new_name="last_ip",
        ),
    ]
