# Generated by Django 3.1.7 on 2021-04-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_post_renew'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='cache_comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='cache_likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='cache_views_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='category_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='user_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
